version: "3.5"
services:
  php_fpm:
      image: dangvantri113/my-laravel-php-fpm:v.0.1
      container_name: blog_php_fpm
      working_dir: /usr/share/nginx/blog
      networks:
        - blog
      volumes:
          - ./:/usr/share/nginx/blog
  nginx:
      image: nginx:1.15
      container_name: blog_nginx
      working_dir: /usr/share/nginx/blog
      networks:
        - blog
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/blog
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
      image: mysql:5.7
      container_name: blog_mysql
      networks:
        - blog
      environment:
        - MYSQL_DATABASE=blog
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=blog
        - MYSQL_PASSWORD=password
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
        - blog
    ports:
      - 9000:8080
networks:
  blog:
    driver: bridge